{{- if .Values.daprComponents.deploy }}
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: {{ .Values.daprComponents.state.name }}
spec:
  type: state.redis
  metadata:
  - name: redisHost
    value: {{ .Values.daprComponents.state.redisHost }}
  - name: redisPassword
    value: ""
{{ end }}